version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - sql_server
    environment:
      - SQL_SERVER_SERVER=sql_server
      - SQL_SERVER_USER=sa
      - SQL_SERVER_PASSWORD=Ndjsl0506
      - SQL_SERVER_DATABASE=SaveMyMoney
    networks:
      - flask_network
    volumes:
      - .:/app
    command: bash -c "sleep 30 && python /app/app.py"

  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Ndjsl0506
    ports:
      - "1433:1433"
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
