version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
        - FLASK_ENV=development
        - SQL_SERVER_DRIVER=ODBC Driver 17 for SQL Server
        - SQL_SERVER_SERVER=192.168.100.48
        - SQL_SERVER_DATABASE=SaveMyMoney
        - SQL_SERVER_USER=sa
        - SQL_SERVER_PASSWORD=Ndjsl0506

    depends_on:
      - sqlserver
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Ndjsl0506
    ports:
      - "1433:1433"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
 

